config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/cars/manage', to: "cars#manage", as: :manage_cars
  resources :cars do
    resources :bookings, only: %i[ new create]
  end
  resources :bookings, only: %i[index show destroy]
  # Defines the root path route ("/")
  # root "articlndex"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user
  validates :car, presence: true
  validates :user, presence: true
  validates :start_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :make, presence: true
  validates :model, presence: true
  validates :year, presence: true, numericality: { only_integer: true }
  validates :transmission, presence: true
  validates :seats, presence: true, numericality: { only_integer: true }
  validates :price_per_day, presence: true, numericality: { only_integer: true }
  validates :class_type, presence: true
  validates :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d-]+(\.[a-z\d-]+)*\.[a-z]+\z/i

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :last_name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :phone_number, presence: true, length: { minimum: 8, maximum: 11 }, numericality: true
  validates :email, length: { minimum: 10, maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  validates :encrypted_password, presence: true, length: { minimum: 6, maximum: 255 }
  validates :password_confirmation, presence: true, length: { minimum: 6, maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :success

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user: current_user)
  end

  def new
    @booking = Booking.new
  end


  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  def create
    begin
      @car = Car.find(params[:car_id])
      start_date = booking_params[:start_date].split(" to ")[0]
      end_date = booking_params[:start_date].split(" to ")[1]
      total_days = (Date.parse(end_date) - Date.parse(start_date)).to_i
      total_price = @car.price_per_day.to_i * total_days
    rescue
      return
    end
    if overlap?(start_date, end_date, @car)
      flash.alert = "Sorry, the selected dates are not available!"
      redirect_to car_path(@car)
      return false
    end
    @booking = Booking.new(
                          start_date: start_date,
                          end_date: end_date,
                          location: "None",
                          total_price: total_price,
                          total_days: total_days,
                          car: @car,
                          user: current_user
                          )
    if @booking.save
      redirect_to booking_path(@booking), success: "Booking created"
    end
  end

  def overlap?(start_date, end_date, car)
    all_ranges = Booking.where(car: car)
    all_ranges.each do |booking|
      if (start_date <= booking.end_date && end_date >= booking.start_date)
        return true
      end
    end
    return false
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @cars = Car.where.not(user: current_user)
    @cars_makes = @cars.uniq { |car| car.make }
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    # raise
    if @car.save
      redirect_to manage_cars_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def manage
    @cars = Car.where(user: current_user)
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to manage_cars_path, status: :see_other
  end

  def edit
    @car = Car.find(params[:id])
    if @car.user != current_user
      redirect_to manage_cars_path
    end
  end

  def update
    @car = Car.find(params[:id])
    if @car.update(car_params)
      redirect_to manage_cars_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @car = Car.find(params[:id])
    past_bookings = []

    @car.bookings.each do |current_booking|
      past_bookings << {from: current_booking.start_date.strftime("%Y-%m-%d"),to: current_booking.end_date.strftime("%Y-%m-%d")}
    end
    @bookings = past_bookings.to_json
    @booking = Booking.new
  end

  private

  def car_params
    params.require(:car).permit(:make, :model, :year, :transmission, :seats, :air_conditioning, :price_per_day, :class_type, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<% title = 'My Bookings' %>
<% subtitle = "View and Manage your past, current and future Bookings!" %>
<% paragraph = "" %>
<% background_img_mini_bar = 'https://images.unsplash.com/photo-1530685932526-48ec92998eaa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80' %>
<%= render "shared/mininavbar", title: title, subtitle: subtitle, paragraph: paragraph, background_img_mini_bar: background_img_mini_bar %>

<div class="container mt-3 p-3 bg-white shadow rounded">
  <% if @bookings.count.zero? %>
    <div class="alert alert-secondary" role="alert">
      You have no reservations yet. Fancy one? Please click <%= link_to "here", cars_path, class: "alert-link" %>.
    </div>
  <% end %>

  <% @bookings.each do |booking| %>
    <div class="container mt-5 mb-5 border">
      <div class="row d-flex justify-content-left">
        <div class="col-md-4" style="padding:0">
          <div class="card rounded">
            <%= cl_image_tag booking.car.photo.key, width: 500, height: 300, crop: :fill, class: "img-fluid rounded hover01" %>
          </div>
        </div>
        <div class="col-md-5 border-right">
          <div class="border-right">
            <span class="text-uppercase text-muted brand"><%= booking.car.year %></span>
            <h5 class="text-uppercase"><%= booking.car.make %> - <%= booking.car.model %></h5>
            <p class="card-text text-muted card-booking">
              <div class= "tooltip-wrap text-muted">
              <i class="fa-solid fa-calendar m-2"></i>
              Your renting is going to start from
              <strong><%= booking.start_date.strftime "%d/%m/%Y" %></strong> to
              <strong><%= booking.end_date.strftime "%d/%m/%Y" %></strong>
              <span class="text-muted">| <%= pluralize(booking.total_days, 'day') %> |
              <i class="fa-solid fa-circle-question tooltip-wrap"></i>
               <div class="tooltip-content fst-italic">
                  Remember to return your car by 12
              </div>
              </div>
              </span>
            </p>
            <p class="card-text text-muted">
              <i class="fa-solid fa-dollar-sign m-2"></i>
              The total price of your renting is <strong><%= booking.total_price %> €</strong>
            </p>
            <div>

            </div>
          </div>
        </div>
        <div class="col-md-3 justify-content-center">
          <h5 class="text-uppercase mt-4"> The specs of your car</h5>
          <i class="fa-solid fa-car text-muted"></i> <%= booking.car.transmission %> |
          <span class="act-price">
            <span data-flatpickr-target="carPrice"><%= booking.car.price_per_day %></span>€
            <i class="text-muted"> per day</i>
          </span>
          <div class="mt-2">
            <i class="fa-solid fa-chair text-muted"></i> Seats: <span class="text-muted"><%= booking.car.seats %></span>
            <i class="text-muted"> |
            <i class="fa-solid fa-flag-checkered ms-2 text-muted"></i>
            <span class="text-muted"><%= booking.car.class_type %></span>
            </i>
          </div>
          <div class="mt-2">
            Air Conditioning:
            <% if booking.car.air_conditioning %>
              <i class="fa-solid fa-circle-check text-success text-muted"></i>
            <% else %>
              <i class="fa-solid fa-circle-xmark text-danger text-muted"></i>
            <% end %>
             <%= link_to "Cancel your reservation", booking_path(booking), class: "button btn btn-danger text-white mt-4",
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
          </div>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/bookings/new.html.erb
<div class="container shadow rounded-3 bg-light my-2 p-3">
  <div class="form-inputs">
    <%= simple_form_for @booking do |f| %>
      <%= f.input :start_date,
                  required: true,
                  input_html: {autocomplete: "Start date needed" }%>
      <%= f.button :submit, "Create my Booking", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
 <% title = 'Thanks for your reservation' %>
    <% subtitle = "Here are the details"%>
    <% paragraph = "" %>
    <% background_img_mini_bar = 'https://images.unsplash.com/photo-1530685932526-48ec92998eaa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80' %>
    <%= render "shared/mininavbar", title: title, subtitle: subtitle, paragraph: paragraph, background_img_mini_bar: background_img_mini_bar %>

<div class="container shadow rounded-3 bg-light my-2 p-3">
  <div class="row">
    <div class="col-md-4 offset-4">
      <h5 class="text-muted px-1"><i class="fa-solid fa-receipt"></i> Booking and Payment Details</h5>
      <table class="table">
        <tbody>
          <tr>
            <td>Car Rented</td>
            <td><%= "#{@booking.car.make} #{@booking.car.model}" %></td>
          </tr>
          <tr>
            <td>Rental Dates</td>
            <td><%= "#{@booking.start_date.strftime('%Y-%m-%d')} - #{@booking.end_date.strftime('%Y-%m-%d')}" %></td>
          </tr>
           <tr>
            <td>Rented from</td>
            <td><%= "#{@booking.car.user.first_name} #{@booking.car.user.last_name}" %></td>
          </tr>
           <tr>
            <td>Total Paid</td>
            <td>&euro;<%= "#{@booking.total_price}" %>.00</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-4 d-flex align-items-center">
      <%= link_to  "Manage Your Bookings", bookings_path, class: "btn btn-primary text-white" %>
    </div>
  </div>
</div>

app/views/cars/edit.html.erb
 <% title = 'Manage your fleet' %>
    <% subtitle = "Edit car details for #{@car.make} #{@car.model}"%>
    <% paragraph = "" %>
    <% background_img_mini_bar = 'https://images.unsplash.com/photo-1530685932526-48ec92998eaa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80' %>
    <%= render "shared/mininavbar", title: title, subtitle: subtitle, paragraph: paragraph, background_img_mini_bar: background_img_mini_bar %>

<div class="container shadow rounded-3 bg-light my-2 p-3">
    <h4 class="text-muted">Please make your changes here</h4>
    <hr>

    <div class="form-inputs">
    <%= simple_form_for @car do |f| %>
      <div class="row">
      <div class="col-6">
      <%= f.input :make,
                  required: true,
                  input_html: { autocomplete: "Make nedded" }%>
      </div>
      <div class="col-6">
      <%= f.input :class_type,
                  collection: %w(SUV Hatchback Sedan Coupe Convertible Minivan Wagon Crossover SportsCar),
                  required: true,
                  input_html: { autocomplete: "Car type nedded" }%>
      </div>
      <div class="col-6">
      <%= f.input :model,
                  required: true,
                  input_html: { autocomplete: "Model nedded" }%>
      </div>
      <div class="col-6">
      <%= f.input :year,
                  required: true,
                  input_html: { autocomplete: "Year nedded" }%>
      </div>
      <div class="col-6">
      <%= f.input :transmission,
                  collection: [ "Automatic", "Manual",],
                  required: true,
                  input_html: { autocomplete: "Transmission nedded" }%>
      </div>
      <div class="col-6">
      <%= f.input :seats,
                  required: true,
                  collection: 1..8,
                  input_html: { autocomplete: "Seats nedded" }%>
      </div>
      <div class="col-6">
      <%= f.input :price_per_day,
                  required: true,
                  input_html: { autocomplete: "Price x day nedded" }%>
       </div>
      <div class="col-6">
                  <%= f.input :photo, as: :file %>
      </div>
      <div class="col-6 align-items-center">
      <%= f.input :air_conditioning,
                  required: true,
                  input_html: { autocomplete: "AC nedded" }%>
       </div>

      <%= f.button :submit, "Edit Car Details", class: "btn btn-danger text-white mt-4" %>
    <% end %>

  </div>
  </div>
</div>

app/views/cars/manage.html.erb
<% title = 'Manage your fleet' %>
<% subtitle = 'You can remove and edit your own cars here!' %>
<% paragraph = "You have a total of  #{pluralize(@cars.count, 'car')} in your fleet" %>
<% background_img_mini_bar = 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80' %>
<%= render "shared/mininavbar", title: title, subtitle: subtitle, paragraph: paragraph, background_img_mini_bar: background_img_mini_bar %>
<div class="container mt-3 p-3 bg-white shadow">
  <% if @cars.count.zero? %>
        <div class="alert alert-secondary" role="alert">
      You have't created a car yet. Do you want to create a <strong>new one</strong>? Please click  <%= link_to "here", new_car_path, class: "alert-link" %>.
        </div>
        <% end %>
  <% @cars.each do |car| %>
    <div class="card m-3 shadow-sm card-car bg-light">
      <div class="row g-0">
        <div class="col-md-3">
          <%= cl_image_tag car.photo.key, width: 300, height: 175, crop: :fill, class: "img-fluid"%>
        </div>
        <div class="col-md-9 ">
          <div class="card-body bg-light">
            <p class="card-title text-secondary "> <span class="fs-4 fw-light text-uppercase"> <%= car.make%> <%= car.model%></span>
              <span class="text-muted float-end">
                <%= car.year %>
                /
                <i class="fa-solid fa-car"></i> <%= car.transmission %>
                /
                <i class="fa-solid fa-chair"></i> Seats: <%= car.seats %>
              </span>
            </p>
            <div class="row mt-2 px-3">
              <div class="col-4 text-muted">
                <p>
                  <span class="fw-semibold">Air Conditioning:</span>
                  <% if car.air_conditioning %>
                    <i class="fa-solid text-success fa-circle-check"></i>
                  <% else %>
                    <i class="fa-solid text-danger fa-circle-xmark"></i>
                  <% end %>
                </p>
                <p><span class="fw-semibold"> Class:</span> <%= car.class_type %></p>
              </div>
              <div class="col-8 d-flex align-items-end justify-content-end">
                <button class=" btn btn-dark float-end price">Price Per Day: &euro;<%= car.price_per_day %></button>
                <%= link_to "Delete", car_path(car), class: "btn btn-danger text-white float-end",
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
                <%= link_to "Edit Details", edit_car_path(car), class: "btn btn-primary text-white" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/cars/show.html.erb
<% title = "You are trying to rent #{@car.year} #{@car.make} #{@car.model}" %>
<% subtitle = 'Please choose your dates' %>
<% paragraph = '' %>
<% background_img_mini_bar = 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80' %>
<%= render "shared/mininavbar", title: title, subtitle: subtitle, paragraph: paragraph, background_img_mini_bar: background_img_mini_bar %>
<div class="container mt-5 mb-5">
  <div class="row d-flex justify-content-center">
    <div class="col-md-10">
      <div class="card shadow rounded" data-controller="flatpickr">
        <div class="row">
          <div class="col-md-6">
            <div class="images p-3">
              <div class="text-center mt-2 "><%= cl_image_tag @car.photo.key, height: 250, width: 400, class: "shadow mb-5 bg-body rounded border border-secondary" ,crop: :fill %> </div>
             <div class="text-start text-muted ms-5" style="font-size:15px;"><i class="fa-solid fa-square-check"></i> Posted by <i><%= "#{@car.user.first_name} #{@car.user.last_name} at #{@car.created_at.strftime("%d/%m/%Y")}" %></i>
              <br><i class="fa-solid fa-credit-card"></i> Booked a total of <%= @car.bookings.count %> times
             </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="product p-4">
              <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center"><i class=></i> <span class="">
                    <%= link_to cars_path, class: 'btn', style: "margin-left:-15px;" do %>
                      <i class="fa fa-long-arrow-left"></i>
                      Back
                    <% end %>
                  </span> </div>
              </div>
              <div class="mt-4 mb-3"> <span class="text-uppercase text-muted brand"><%= @car.year %></span>
                <h5 class="text-uppercase"><%= @car.make.capitalize %> - <%= @car.model.capitalize %></h5>
                <div class="price d-flex flex-row align-items-center">
                  <span class="act-price"><span  data-flatpickr-target="carPrice"><%= @car.price_per_day %></span>€<i class="text-muted"> per day</i></span>
                </div>
              </div>
              <p class="about">
                <i class="fa-solid fa-car"></i> <%= @car.transmission %>
                /
                <i class="fa-solid fa-chair"></i> Seats: <%= @car.seats %>
                /
                <i class="">
                  Air Conditioning:
                  <% if @car.air_conditioning %>
                    <i class="fa-solid text-muted fa-circle-check"></i>
                  <% else %>
                    <i class="fa-solid text-muted fa-circle-xmark"></i>
                  <% end %>
                </p>
              </i>
                <hr class="text-muted mt-3">
                <h5 class="text-muted">Book This Car</h5>
                <%= simple_form_for [@car, @booking] do |f| %>
                  <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_disable_value: @bookings, flatpickr_target: "rangeDate", action: "change->flatpickr#calculate" }, required: true} %>
                  <div class = "d-flex align-items-center">
                  <%= f.submit 'Confirm Booking', class: "btn btn-danger text-white",  data: { flatpickr_target: "submitButton" }  %>
                <% end %>
                <p class="text-center text-muted mx-3 mt-3"><span data-flatpickr-target="price"> </span> </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1610647752706-3bb12232b3ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1025&q=80);">
  <div class="container">
    <h1>Rent a car <strong data-controller="typed-js"> </strong></h1>
    <p>Find yourself in a hurry? Our offer is varied and unique. Instant access to over 40,000 vehicles in Spain!</p>
    <%= link_to "Rent a Car", cars_path, class: "btn btn-danger text-white" %>
  </div>


</div>

<div class="container mt-3"
<section>
  <div class="row d-flex justify-content-center">
    <div class="col-md-10 col-xl-8 text-center">
      <h3 class="mb-4">Testimonials</h3>
      <p class="mb-4 pb-2 mb-md-5 pb-md-0">
        This is what our customers think about us!
      </p>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-md-4 mb-5 mb-md-0">
      <div class="d-flex justify-content-center mb-4">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).webp"
          class="rounded-circle shadow-1-strong" width="150" height="150" />
      </div>
      <h5 class="mb-3">Maria Smantha</h5>
      <h6 class="text-primary mb-3">Booked 3 times!</h6>
      <p class="px-xl-3">
        <i class="fas fa-quote-left pe-2"></i>Lorem ipsum dolor sit amet, consectetur
        adipisicing elit. Quod eos id officiis hic tenetur quae quaerat ad velit ab hic
        tenetur.
      </p>
      <ul class="list-unstyled d-flex justify-content-center mb-0">
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="fas fa-star-half-alt fa-sm text-warning"></i>
        </li>
      </ul>
    </div>
    <div class="col-md-4 mb-5 mb-md-0">
      <div class="d-flex justify-content-center mb-4">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).webp"
          class="rounded-circle shadow-1-strong" width="150" height="150" />
      </div>
      <h5 class="mb-3">Lisa Cudrow</h5>
      <h6 class="text-primary mb-3">Has a fleet of 6 cars!</h6>
      <p class="px-xl-3">
        <i class="fas fa-quote-left pe-2"></i>Ut enim ad minima veniam, quis nostrum
        exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid commodi.
      </p>
      <ul class="list-unstyled d-flex justify-content-center mb-0">
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
      </ul>
    </div>
    <div class="col-md-4 mb-0">
      <div class="d-flex justify-content-center mb-4">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).webp"
          class="rounded-circle shadow-1-strong" width="150" height="150" />
      </div>
      <h5 class="mb-3">John Smith</h5>
      <h6 class="text-primary mb-3">Booked 2 times!</h6>
      <p class="px-xl-3">
        <i class="fas fa-quote-left pe-2"></i>At vero eos et accusamus et iusto odio
        dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti.
      </p>
      <ul class="list-unstyled d-flex justify-content-center mb-0">
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="fas fa-star fa-sm text-warning"></i>
        </li>
        <li>
          <i class="far fa-star fa-sm text-warning"></i>
        </li>
      </ul>
    </div>
  </div>
</section>

<section>


</section>
</div>

app/views/shared/_mininavbar.html.erb
<div class="mini-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= background_img_mini_bar %>;);">
  <div class="container">
    <h1> <%= title %> </h1>
    <p> <%= subtitle %> </p>
      <h2 class=""> <%= paragraph %> </h2>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon shadow">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active hover-underline-animation">
            <%= link_to "Home", root_path, class: "nav-link mx-3" %>
          </li>
          <li class="nav-item hover-underline-animation">
            <%= link_to 'Rent a Car', cars_path, class: "nav-link mx-3" %>
          </li>
          <li class="nav-item hover-underline-animation">
            <%= link_to "My Bookings", bookings_path, class: "nav-link mx-3" %>
          </li>
          <li class="nav-item hover-underline-animation">
            <%= link_to "Manage Fleet", manage_cars_path, class: "nav-link mx-3" %>
          </li>
          <li class="nav-item hover-underline-animation">
            <%= link_to "Post an Ad", new_car_path, class: "nav-link mx-3" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://i.pinimg.com/474x/c9/bc/a5/c9bca57cf02ef46be89630414a89b5f5.jpg", class: "avatar", style: "width:30px;padding-top:5px;", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", edit_user_registration_path , class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>